/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frame;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import koneksi.database;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Statement;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author User
 */
public class FormAbsensi extends javax.swing.JFrame {

    private database obj;
    private DefaultTableModel modelTabelAbsensi;
    
    
    /**
     * Creates new form FormAbsensi
     */
    public FormAbsensi() {
        initComponents();
               this.setLocationRelativeTo(null);
        
        obj = new database();
        modelTabelAbsensi = new DefaultTableModel();
        TabelAbsensi.setModel(modelTabelAbsensi);
        modelTabelAbsensi.addColumn("ID ABSENSI");
        modelTabelAbsensi.addColumn("ID PEGAWAI");
        modelTabelAbsensi.addColumn("TANGGAL");
        modelTabelAbsensi.addColumn("JAM MASUK");
        modelTabelAbsensi.addColumn("JAM KELUAR");
        tampilDataAbsensi();
        
    }
    
    public void tampilDataAbsensi() {
         try {
            modelTabelAbsensi.setRowCount(0);

            String query = "SELECT * FROM tb_absensi";
            try (PreparedStatement preparedStatement = obj.konek.prepareStatement(query);
                 ResultSet data = preparedStatement.executeQuery()) {
                while (data.next()) {
                    Object[] line = new Object[5];
                    line[0] = data.getString("id_absensi");
                    line[1] = data.getString("id_pegawai");
                    line[2] = data.getString("tanggal");
                    line[3] = data.getString("jam_masuk");
                    line[4] = data.getString("jam_keluar");
                    modelTabelAbsensi.addRow(line);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfIdAbsensi = new javax.swing.JTextField();
        tfIdPegawai = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelAbsensi = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfTanggal = new javax.swing.JTextField();
        tfJamMasuk = new javax.swing.JTextField();
        tfJamKeluar = new javax.swing.JTextField();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Form Absensi"));
        jPanel1.setForeground(new java.awt.Color(255, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("ID Absensi");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("ID Pegawai");

        tfIdAbsensi.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        tfIdPegawai.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        TabelAbsensi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelAbsensi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelAbsensiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelAbsensi);

        btnSimpan.setBackground(new java.awt.Color(204, 204, 204));
        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnUbah.setBackground(new java.awt.Color(204, 204, 204));
        btnUbah.setText("UBAH");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(204, 204, 204));
        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(204, 204, 204));
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnCetak.setBackground(new java.awt.Color(204, 204, 204));
        btnCetak.setText("CETAK");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tanggal");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Jam Masuk");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Jam Keluar");

        tfTanggal.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tfTanggal.setText("00/00/00");

        tfJamMasuk.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tfJamMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfJamMasukActionPerformed(evt);
            }
        });

        tfJamKeluar.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        btnKeluar.setBackground(new java.awt.Color(204, 204, 204));
        btnKeluar.setText("KELUAR");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfIdAbsensi, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(tfTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfIdPegawai)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfJamMasuk)
                            .addComponent(tfJamKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSimpan)
                            .addComponent(btnHapus))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(btnUbah))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(btnClear)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCetak)
                            .addComponent(btnKeluar))
                        .addGap(121, 121, 121)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfIdAbsensi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfIdPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfJamMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfJamKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUbah)
                            .addComponent(btnSimpan)
                            .addComponent(btnCetak)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus)
                    .addComponent(btnClear)
                    .addComponent(btnKeluar))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
      try {
        if (tfIdAbsensi.getText().isEmpty() || tfIdPegawai.getText().isEmpty() ||
            tfTanggal.getText().isEmpty() || tfJamMasuk.getText().isEmpty() || tfJamKeluar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Silahkan isi semua data terlebih dahulu!");
        } else {
        // Bagian untuk INSERT
        String sqlInsert = "INSERT INTO tb_absensi (id_absensi, id_pegawai, tanggal, jam_masuk, jam_keluar) " +
                           "VALUES (?, ?, ?, ?, ?)";
        PreparedStatement insertStmt = obj.konek.prepareStatement(sqlInsert);

        insertStmt.setString(1, tfIdAbsensi.getText());
        insertStmt.setString(2, tfIdPegawai.getText());
        insertStmt.setString(3, tfTanggal.getText());
        insertStmt.setString(4, tfJamMasuk.getText());
        insertStmt.setString(5, tfJamKeluar.getText());

        // Bagian untuk UPDATE
        String sqlUpdate = "UPDATE tb_absensi SET id_pegawai=?, tanggal=?, jam_masuk=?, " +
                           "jam_keluar=? WHERE id_absensi=?";
        PreparedStatement updateStmt = obj.konek.prepareStatement(sqlUpdate);

        updateStmt.setString(1, tfIdPegawai.getText());
        updateStmt.setString(2, tfTanggal.getText());
        updateStmt.setString(3, tfJamMasuk.getText());
        updateStmt.setString(4, tfJamKeluar.getText());
        updateStmt.setString(5, tfIdAbsensi.getText());

        // Eksekusi query UPDATE
        int hasilUpdate = updateStmt.executeUpdate();

        // Jika tidak ada baris yang terpengaruh (data tidak ada), eksekusi query INSERT
        if (hasilUpdate == 0) {
            int hasilInsert = insertStmt.executeUpdate();

            if (hasilInsert > 0) {
                tampilDataAbsensi();
                JOptionPane.showMessageDialog(this, "Data Berhasil Diubah!");
            } else {
                JOptionPane.showMessageDialog(this, "Gagal mengubah data. Pastikan ID Absensi yang dimasukkan benar.");
            }
        } else {
            tampilDataAbsensi();
            JOptionPane.showMessageDialog(this, "Data Berhasil Diubah!");
        }
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
      try {
        // Mengecek apakah kolom input ID Absensi, ID Pegawai, Tanggal, Jam Masuk, dan Jam Keluar kosong
        if (tfIdAbsensi.getText().isEmpty() && tfIdPegawai.getText().isEmpty()
                && tfTanggal.getText().isEmpty() && tfJamMasuk.getText().isEmpty()
                && tfJamKeluar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Silahkan pilih data terlebih dahulu!");
        } else {
            // Menampilkan dialog konfirmasi sebelum menghapus
            int confirmDialogResult = JOptionPane.showConfirmDialog(this,
                    "Apakah Anda yakin ingin menghapus data?", "Konfirmasi Hapus",
                    JOptionPane.YES_NO_OPTION);

            // Jika pengguna mengonfirmasi untuk menghapus
            if (confirmDialogResult == JOptionPane.YES_OPTION) {
                // Query SQL untuk menghapus data dari tabel absensi
                String sql = "DELETE FROM tb_absensi WHERE id_absensi=?";
                
                // Menggunakan try-with-resources untuk PreparedStatement
                try (PreparedStatement hapus = obj.konek.prepareStatement(sql)) {
                    hapus.setString(1, tfIdAbsensi.getText());
                    
                    // Menjalankan query DELETE dan mendapatkan jumlah baris yang terpengaruh
                    int rowsAffected = hapus.executeUpdate();

                    // Jika ada baris yang terpengaruh, berarti data berhasil dihapus
                    if (rowsAffected > 0) {
                        tampilDataAbsensi();
                        JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus!");
                    } else {
                        // Jika tidak ada baris yang terpengaruh, berarti data tidak ditemukan
                        JOptionPane.showMessageDialog(this, "Gagal menghapus data. Data tidak ditemukan.");
                    }
                }
            }
        }
    } catch (SQLException | HeadlessException e) {
        // Menangani kesalahan dan menampilkan pesan kesalahan kepada pengguna
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        tfIdAbsensi.setText("");
        tfIdPegawai.setText("");
        tfTanggal.setText("");
        tfJamMasuk.setText("");
        tfJamKeluar.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void tfJamMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfJamMasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfJamMasukActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try {
           if (tfIdAbsensi.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "ID Absen belum di isi");
               tfIdAbsensi.requestFocus();
           } else if (tfIdPegawai.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "ID Pegawai belum diisi");
               tfIdPegawai.requestFocus();
           } else if (tfTanggal.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Tanggal belum diisi");
               tfTanggal.requestFocus();
           } else if (tfJamMasuk.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Jam Masuk belum diisi");
               tfJamMasuk.requestFocus();
           } else if (tfJamKeluar.getText().isEmpty()) {
               JOptionPane.showMessageDialog(this, "Jam Keluar belum diisi");
               tfJamKeluar.requestFocus();
           } else {
               String sql = "insert into tb_absensi value('"+tfIdAbsensi.getText()+"','"+tfIdPegawai.getText()+"','"+tfTanggal.getText()+"','"+tfJamMasuk.getText()+"','"+tfJamKeluar.getText()+"')";
               obj.konek.createStatement().execute(sql);
               JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan");
           }
           tampilDataAbsensi();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void TabelAbsensiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelAbsensiMouseClicked
        int baris = TabelAbsensi.getSelectedRow();
        String id_absensi = TabelAbsensi.getValueAt(baris, 0).toString();
        String id_pegawai = TabelAbsensi.getValueAt(baris, 1).toString();
        String tanggal = TabelAbsensi.getValueAt(baris, 2).toString();
        String jam_masuk = TabelAbsensi.getValueAt(baris, 3).toString();
        String jam_keluar = TabelAbsensi.getValueAt(baris, 4).toString();
        tfIdAbsensi.setText(id_absensi);
        tfIdPegawai.setText(id_pegawai);
        tfTanggal.setText(tanggal);
        tfJamMasuk.setText(jam_masuk);
        tfJamKeluar.setText(jam_keluar);
    }//GEN-LAST:event_TabelAbsensiMouseClicked

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        String path = ".\\src\\report\\LaporanAbsensi.jasper";
        try {
        // Mengatur koneksi database (gantilah parameter koneksi dengan yang sesuai)
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbkepegawaian", "root", "");

        // Mengisi laporan dengan data dari database
        JasperPrint jprint = JasperFillManager.fillReport(path, null, conn);

        // Menampilkan laporan menggunakan JasperViewer
        JasperViewer jviewer = new JasperViewer(jprint, false);
        jviewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        jviewer.setVisible(true);

        // Menutup koneksi database setelah selesai
        conn.close();
     } catch (JRException | SQLException e) {
        // Menangkap dan menampilkan exception
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
     }
    }//GEN-LAST:event_btnCetakActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        new FormUtama().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAbsensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAbsensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAbsensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAbsensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAbsensi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelAbsensi;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfIdAbsensi;
    private javax.swing.JTextField tfIdPegawai;
    private javax.swing.JTextField tfJamKeluar;
    private javax.swing.JTextField tfJamMasuk;
    private javax.swing.JTextField tfTanggal;
    // End of variables declaration//GEN-END:variables
}
